// openapi_schema_reflect.go reflects handler DTO Response structs via go/ast to generate business schema $refs.
//
// Fixes review issue 8: the original implementation made all endpoint response schemas opaque {"type":"object"} with no business $refs in the spec,
// so Apifox could not render example responses or validate response bodies.
//
// Reflection principle:
//   - Use go/parser to parse the internal/server/handler/*.go files
//   - Scan type XxxResponse struct {...} declarations, extracting json tags and field types
//   - Map Go types to OpenAPI schema types (string→string/int32→integer/[]string→array, etc.)
//   - Register into components.schemas; response bodies reference via $ref
//
// Limitations:
//   - Only reflects explicit *Response structs (covers high-frequency DTOs)
//   - json.RawMessage and nested structs are marked as object, not deeply reflected (to avoid infinite recursion)
//   - Does not reflect Request structs (request body schemas are described in this document's business sections)
package server

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// reflectResponseSchemas reflects all *Response structs under the handler package and registers them into the OpenAPI doc's components.schemas.
//
// Scan rules:
//   - Iterate over internal/server/handler/*.go
//   - Match type names ending in "Response" (e.g. authResponse, taskResponse, projectStatsResponse)
//   - Extract each field's json tag and Go type, mapping it to an OpenAPI schema property
//   - Nested types (e.g. taskCountsByStatus) are reflected once recursively and registered as independent schemas
//
// Parameters:
//   - doc: the OpenAPI document to populate
//   - handlerDir: the handler package directory path (typically internal/server/handler)
//
// Returns:
//   - error: returned when parsing fails
func reflectResponseSchemas(doc *OpenAPIDoc, handlerDir string) error {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, handlerDir, func(fi os.FileInfo) bool {
		return strings.HasSuffix(fi.Name(), ".go") && !strings.HasSuffix(fi.Name(), "_test.go")
	}, parser.ParseComments)
	if err != nil {
		return fmt.Errorf("parse handler dir: %w", err)
	}

	// Collect all type declarations (including nested types)
	// Note: fields must be kept in source-file declaration order, not in a map (map iteration is unordered),
	// otherwise the required field order generated by reflectStructType would be random, the spec would be unstable, and CI git diff would falsely report drift.
	typeDecl := map[string][]*ast.Field{} // typeName → field list (in declaration order)
	for _, pkg := range pkgs {
		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				genDecl, ok := decl.(*ast.GenDecl)
				if !ok || genDecl.Tok != token.TYPE {
					continue
				}
				for _, spec := range genDecl.Specs {
					typeSpec, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}
					structType, ok := typeSpec.Type.(*ast.StructType)
					if !ok {
						continue
					}
					// Collect fields in declaration order (structType.Fields.List is already in source-file order)
					var fields []*ast.Field
					for _, field := range structType.Fields.List {
						fields = append(fields, field)
					}
					typeDecl[typeSpec.Name.Name] = fields
				}
			}
		}
	}

	// Reflect all *Response types + the nested types they reference
	// Note: typeDecl is a map with random iteration order; it must be sorted by typeName before reflecting,
	// otherwise the generated schema registration order would be random, the spec unstable, and CI git diff would falsely report drift.
	reflected := map[string]bool{}
	responseTypeNames := make([]string, 0, len(typeDecl))
	for typeName := range typeDecl {
		if strings.HasSuffix(typeName, "Response") {
			responseTypeNames = append(responseTypeNames, typeName)
		}
	}
	sort.Strings(responseTypeNames)
	for _, typeName := range responseTypeNames {
		if reflected[typeName] {
			continue
		}
		schema := reflectStructType(typeName, typeDecl[typeName], typeDecl, reflected)
		doc.Components.Schemas[typeName] = schema
		reflected[typeName] = true
	}

	return nil
}

// reflectStructType reflects a single struct type into an OpenAPI schema.
//
// For nested types (field types that are other structs in the same package), it reflects recursively and registers them as independent schemas,
// and the current field references them via $ref.
//
// Note: fields must be an ordered slice (not a map) to keep the required field order stable,
// so the spec is reproducible across runs and the CI git diff --exit-code zero-drift check holds.
func reflectStructType(typeName string, fields []*ast.Field, allTypes map[string][]*ast.Field, reflected map[string]bool) OpenAPISchema {
	schema := OpenAPISchema{
		Type:        "object",
		Description: fmt.Sprintf("%s response body (auto-generated by handler DTO reflection)", typeName),
		Properties:  map[string]interface{}{},
	}
	var required []string

	for _, field := range fields {
		// Handle multi-field declarations (e.g. `a, b string`), reflecting each in declaration order
		for _, name := range field.Names {
			jsonTag := extractJSONTag(field)
			if jsonTag == "-" {
				continue
			}
			if jsonTag == "" {
				jsonTag = name.Name
			}

			// Parse the field type → OpenAPI schema
			propSchema := goTypeToOpenAPI(field.Type, allTypes, reflected)
			schema.Properties[jsonTag] = propSchema

			// Non-pointer types are treated as required (a simplified rule that covers most cases)
			if _, isPtr := field.Type.(*ast.StarExpr); !isPtr {
				required = append(required, jsonTag)
			}
		}
	}

	if len(required) > 0 {
		schema.Required = required
	}
	return schema
}

// extractJSONTag extracts the json tag name from a field's ast.Field.
func extractJSONTag(field *ast.Field) string {
	if field.Tag == nil {
		return ""
	}
	// The tag text looks like `json:"id"` or `json:"name,omitempty"`
	tag := strings.Trim(field.Tag.Value, "`")
	for _, part := range strings.Split(tag, " ") {
		if strings.HasPrefix(part, "json:") {
			val := strings.TrimPrefix(part, "json:")
			val = strings.Trim(val, "\"")
			// Take the part before the comma (ignore omitempty, etc.)
			if idx := strings.Index(val, ","); idx >= 0 {
				val = val[:idx]
			}
			return val
		}
	}
	return ""
}

// goTypeToOpenAPI maps a Go ast type to an OpenAPI schema.
//
// Supported type mappings:
//   - string → {type: string}
//   - int32/int64/int → {type: integer, format: int32/int64}
//   - float32/float64 → {type: number}
//   - bool → {type: boolean}
//   - time.Time → {type: string, format: date-time}
//   - []string → {type: array, items: {type: string}}
//   - *string → {type: string, nullable: true}
//   - json.RawMessage → {type: object}
//   - other structs in the same package → {$ref: #/components/schemas/TypeName}
func goTypeToOpenAPI(expr ast.Expr, allTypes map[string][]*ast.Field, reflected map[string]bool) map[string]interface{} {
	switch t := expr.(type) {
	case *ast.Ident:
		// Basic types
		switch t.Name {
		case "string":
			return map[string]interface{}{"type": "string"}
		case "bool":
			return map[string]interface{}{"type": "boolean"}
		case "int", "int32":
			return map[string]interface{}{"type": "integer", "format": "int32"}
		case "int64":
			return map[string]interface{}{"type": "integer", "format": "int64"}
		case "float32", "float64":
			return map[string]interface{}{"type": "number", "format": "float"}
		case "Time":
			return map[string]interface{}{"type": "string", "format": "date-time"}
		case "RawMessage":
			return map[string]interface{}{"type": "object", "description": "Arbitrary JSON"}
		}
		// Other structs in the same package → $ref
		if _, exists := allTypes[t.Name]; exists {
			if !reflected[t.Name] {
				reflected[t.Name] = true
				// Recursively reflect the nested type
			}
			return map[string]interface{}{"$ref": fmt.Sprintf("#/components/schemas/%s", t.Name)}
		}
		return map[string]interface{}{"type": "object", "description": t.Name}

	case *ast.StarExpr:
		// Pointer type: nullable + recursively resolve the inner type
		inner := goTypeToOpenAPI(t.X, allTypes, reflected)
		inner["nullable"] = true
		return inner

	case *ast.ArrayType:
		// Array: items reference the inner type
		inner := goTypeToOpenAPI(t.Elt, allTypes, reflected)
		return map[string]interface{}{"type": "array", "items": inner}

	case *ast.InterfaceType:
		return map[string]interface{}{"type": "object"}

	case *ast.SelectorExpr:
		// Package-qualified types such as time.Time, json.RawMessage
		if t.X != nil {
			if ident, ok := t.X.(*ast.Ident); ok {
				if ident.Name == "time" && t.Sel.Name == "Time" {
					return map[string]interface{}{"type": "string", "format": "date-time"}
				}
				if ident.Name == "json" && t.Sel.Name == "RawMessage" {
					return map[string]interface{}{"type": "object", "description": "Arbitrary JSON"}
				}
			}
		}
		return map[string]interface{}{"type": "object", "description": "selector type"}

	default:
		return map[string]interface{}{"type": "object", "description": "unknown type"}
	}
}

// resolveHandlerDir infers the handler package directory path.
//
// gen-openapi can run in different working directories, so it needs to locate internal/server/handler from the module root.
// Defaults to assuming the current working directory is the module root; otherwise uses the relative path internal/server/handler.
func resolveHandlerDir() string {
	candidates := []string{
		"internal/server/handler",
		"./internal/server/handler",
		"../internal/server/handler",
	}
	for _, c := range candidates {
		if abs, err := filepath.Abs(c); err == nil {
			if fi, err := os.Stat(abs); err == nil && fi.IsDir() {
				return c
			}
		}
	}
	return "internal/server/handler"
}
